const BUILDING_TYPES = {
  COMMERCIAL: "商业",
  RESIDENTIAL: "住宅",
  OFFICE: "办公",
};

const buildings = [
  {
    id: 1,
    name: "星辰商业中心",
    type: BUILDING_TYPES.COMMERCIAL,
    floors: 42,
    energy: 387,
    x: -8,
    z: -6,
    width: 2.5,
    depth: 2.5,
    height: 12,
  },
  {
    id: 2,
    name: "翡翠湾住宅",
    type: BUILDING_TYPES.RESIDENTIAL,
    floors: 18,
    energy: 156,
    x: -4,
    z: -3,
    width: 2,
    depth: 2,
    height: 6,
  },
  {
    id: 3,
    name: "科创大厦",
    type: BUILDING_TYPES.OFFICE,
    floors: 35,
    energy: 312,
    x: 0,
    z: -5,
    width: 2.2,
    depth: 2.2,
    height: 10,
  },
  {
    id: 4,
    name: "悦享广场",
    type: BUILDING_TYPES.COMMERCIAL,
    floors: 28,
    energy: 275,
    x: 5,
    z: -4,
    width: 2.8,
    depth: 2.4,
    height: 8,
  },
  {
    id: 5,
    name: "和园小区",
    type: BUILDING_TYPES.RESIDENTIAL,
    floors: 12,
    energy: 98,
    x: -6,
    z: 2,
    width: 2,
    depth: 2,
    height: 4,
  },
  {
    id: 6,
    name: "云端写字楼",
    type: BUILDING_TYPES.OFFICE,
    floors: 50,
    energy: 425,
    x: -1,
    z: 1,
    width: 2,
    depth: 2,
    height: 14,
  },
  {
    id: 7,
    name: "万象城",
    type: BUILDING_TYPES.COMMERCIAL,
    floors: 22,
    energy: 234,
    x: 4,
    z: 2,
    width: 3,
    depth: 2.5,
    height: 7,
  },
  {
    id: 8,
    name: "碧水雅苑",
    type: BUILDING_TYPES.RESIDENTIAL,
    floors: 16,
    energy: 132,
    x: 8,
    z: 0,
    width: 2,
    depth: 2,
    height: 5.5,
  },
  {
    id: 9,
    name: "数智大厦",
    type: BUILDING_TYPES.OFFICE,
    floors: 38,
    energy: 356,
    x: -3,
    z: 6,
    width: 2.3,
    depth: 2.3,
    height: 11,
  },
  {
    id: 10,
    name: "天街购物中心",
    type: BUILDING_TYPES.COMMERCIAL,
    floors: 20,
    energy: 210,
    x: 2,
    z: 6,
    width: 2.6,
    depth: 2.4,
    height: 6.5,
  },
  {
    id: 11,
    name: "林溪花园",
    type: BUILDING_TYPES.RESIDENTIAL,
    floors: 8,
    energy: 67,
    x: 7,
    z: 5,
    width: 2,
    depth: 2,
    height: 3,
  },
  {
    id: 12,
    name: "汇金中心",
    type: BUILDING_TYPES.OFFICE,
    floors: 45,
    energy: 398,
    x: -7,
    z: -1,
    width: 2.4,
    depth: 2.4,
    height: 13,
  },
  {
    id: 13,
    name: "乐活天地",
    type: BUILDING_TYPES.COMMERCIAL,
    floors: 15,
    energy: 178,
    x: 1,
    z: -1,
    width: 2.5,
    depth: 2,
    height: 5,
  },
  {
    id: 14,
    name: "晴川阁",
    type: BUILDING_TYPES.RESIDENTIAL,
    floors: 24,
    energy: 189,
    x: -5,
    z: 5,
    width: 2,
    depth: 2,
    height: 7.5,
  },
  {
    id: 15,
    name: "未来科技园",
    type: BUILDING_TYPES.OFFICE,
    floors: 30,
    energy: 290,
    x: 6,
    z: -7,
    width: 2.2,
    depth: 2.2,
    height: 9,
  },
  {
    id: 16,
    name: "锦绣家园",
    type: BUILDING_TYPES.RESIDENTIAL,
    floors: 10,
    energy: 82,
    x: -9,
    z: 4,
    width: 2,
    depth: 2,
    height: 3.5,
  },
];

const roads = [
  { id: "h1", startX: -12, startZ: -4.5, endX: 12, endZ: -4.5 },
  { id: "h2", startX: -12, startZ: -0.5, endX: 12, endZ: -0.5 },
  { id: "h3", startX: -12, startZ: 3.5, endX: 12, endZ: 3.5 },
  { id: "v1", startX: -5.5, startZ: -9, endX: -5.5, endZ: 9 },
  { id: "v2", startX: -0.5, startZ: -9, endX: -0.5, endZ: 9 },
  { id: "v3", startX: 3.5, startZ: -9, endX: 3.5, endZ: 9 },
];

const TYPE_COLORS = {
  [BUILDING_TYPES.COMMERCIAL]: "#ff6b35",
  [BUILDING_TYPES.RESIDENTIAL]: "#4ecdc4",
  [BUILDING_TYPES.OFFICE]: "#45b7d1",
};

export { BUILDING_TYPES, buildings, roads, TYPE_COLORS };
